- name: "Install Docker"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"
  become: yes
  gather_facts: no
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'acl']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker
        executable: pip3

    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present

    - name: Add the nucypher user to the docker group
      user:
        name: nucypher
        group: docker

    - name: Download docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: ~/docker-compose
        mode: 'u+x,g+x'

    - name: Check docker-compose exists
      stat: path=~/docker-compose
      register: docker_compose

    - name: Move docker-compose to /usr/local/bin/docker-compose
      command: mv ~/docker-compose /usr/local/bin/docker-compose
      when: docker_compose.stat.exists

    - name: chown docker-compose so nucypher user can use it
      file:
        path: /usr/local/bin/docker-compose
        group: docker

    - name: Ensure Docker has started
      service:
        name: docker
        state: started

    - name: "wait a few seconds for the docker daemon to startup (you can ctrl-C this...)"
      pause:
        seconds: 10
