- name: "Setup Remote Geth"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"

- import_playbook: ../worker/include/setup_user.yml
- import_playbook: ../worker/include/setup_docker.yml
- import_playbook: include/run_monitor.yml
